### ISSUE TITLE
Boostrap REST API framework

### ISSUE THREAD

**Issue by a5anka** [wso2/message-broker#102]
### Description

We can possibly use msf4j to implement the REST API framework in MB4. We are planning to implement following admin services using the framework.

- Queue related REST API
- Subscription related REST APIs
- DLC related REST API
- Topic related REST API

**Comment by a5anka** [comment]
A new class called BrokerContext is introduced in the common module to share different services between the modules. The proposed interface is like below.

![image](https://user-images.githubusercontent.com/1148405/34519066-6415c58e-f0a8-11e7-805b-9d6c09b22f7e.png)

A class called `BrokerServiceRunner` will be exposed from the `rest-service` module via the BrokerContext to be used by all the modules which need to expose rest services. Modules can use the method deploy to register Objects written in MSF4J style.


![image](https://user-images.githubusercontent.com/1148405/34519339-7e118594-f0a9-11e7-9555-58e2f681e954.png)

Sample usage of the service will look something similar to following.

```java
BrokerServiceRunner runner = (BrokerServiceRunner) BrokerContext
                                         .getInstance()
                                         .getService(BrokerServiceRunner.class.getName());
runner.deploy(new QueueService());
```

WDYT?

**Comment by Asitha** [comment]
Shall we get rid of the singleton pattern? +1 for using a BrokerContext.

**Comment by a5anka** [comment]
:+1:. I renamed the class from `BrokerContext` to "StartupContext` since it makes more sense. Modified class will look like below.

![image](https://user-images.githubusercontent.com/1148405/34520388-689ee666-f0ae-11e7-89c2-8180ce69ba2c.png)

Sample usage of the service will look something similar to following.

```java
BrokerServiceRunner runner = (BrokerServiceRunner) StartupContext
                                         .getService(BrokerServiceRunner.class.getName());
runner.deploy(new QueueService());
```

**Comment by a5anka** [comment]
I was able to get rid of the casting using generics. Now the sample code will look like.  

```java
BrokerServiceRunner serviceRunner = startupContext.getService(BrokerServiceRunner.class);
serviceRunner.deploy(new BrokerAdminService())
```
