### ISSUE TITLE
Add generic configuration to set hostname of the server

### ISSUE THREAD

**Issue by warunalakshitha** [wso2/message-broker#137]
**Description:**
We can set the host name at two places as plain hostname and ssl hostname in broker.yaml. But when creating sasl server we need to specify the the fully qualified host name of the server. So we need to have generic element in broker configuration to specify that.

**Comment by a5anka** [comment]
This is fixed in https://github.com/wso2/message-broker/commit/d31c2ba87f717fdef90717fa1cb61291e8b0743b.
