### ISSUE TITLE
[Documentation] Add documentation regarding message broker tables

### ISSUE THREAD

**Issue by fshomou** [wso2/message-broker#170]
**Description:**
Need to explain MB tables in order to understand the Cluster mode vs the Stand-alone mode. 
Need to explain with more details Slot-based message delivery with  Cluster mode.

**Suggested Labels:**
Documenation

**Suggested Assignees:**

**Affected Product Version:**
message-broker 3.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Asitha** [comment]
Hi @fshomou, 

We are maintaining the code base and the issues related to message-broker 3.xx versions at [1].
This repository is for the message-broker 4.xx series.

I have created and issue in carbon-business-messaging repo [2]

[1] https://github.com/wso2/carbon-business-messaging/issues
[2] https://github.com/wso2/carbon-business-messaging/issues/610
