### ISSUE TITLE
Implement Authentication Support 

### ISSUE THREAD

**Issue by warunalakshitha** [wso2/message-broker#61]
**Description:**
This will improve message broker to support authentication.

**Comment by a5anka** [comment]
@warunalakshitha Shall we add the information discussed in architecture mail to this issue.

**Comment by warunalakshitha** [comment]
![image](https://user-images.githubusercontent.com/4163165/34032767-8982a7c0-e19d-11e7-84b2-7db7fdd03160.png)

**Comment by warunalakshitha** [comment]
AMQP specification defined the authentication mechanism and security content data is based on Simple Authentication and Security Layer(SASL) framework. Following figure shows the proposed implementation for $subject.
![image](https://user-images.githubusercontent.com/4163165/34032818-aeca52e4-e19d-11e7-880b-c544853279bb.png)

Once client request  a connection, server will send the supported SASL mechanisms ( ex. Plain Text) to client. After that client will send the selected mechanism + auth response data. Server will create SASL server based on the client mechanism and then server will evaluate the client authentication data and callback handler will be executed for authentication.  It will be done using following two extension points.
Authenticator  - Interface to authenticate mechanism based on security framework .We will use Java Authentication and Authorization Service (JAAS)  as default authentication implementation.
JAAS  Modules - Uses can defined own JAAS Login module as well.
If authentication is success, connection will be established or else will send authentication error.

**Comment by a5anka** [comment]
@warunalakshitha Shall we define the interface of the proposed extension point.

**Comment by warunalakshitha** [comment]
@a5anka Initial proposed implementation had two extension points as follows.

1. Message broker specific authentication.
2. JAAS module.

Since JAAS provides capability to plug-able login modules, we can have only JAAS extension point. 
Extension will be written as Login module and can be specified in jaas.conf as below.

AuthConfig {
   org.wso2.broker.core.security.jaas.CustomLoginModule required;
};

Your custom authentication can be implement in login method and it will return true/false based on authentication result.

`

  @Override
    public boolean login() throws LoginException {
        NameCallback usernameCallback = new NameCallback("username");
        PasswordCallback passwordCallback = new PasswordCallback("password", false);
        Callback[] callbacks = { usernameCallback, passwordCallback };
        try {
            callbackHandler.handle(callbacks);
        } catch (UnsupportedCallbackException e) {
            throw new BrokerLoginException("Callback type does not support. ", e);
        } catch (IOException e) {
            throw new BrokerLoginException("Error occurred while handling  authentication data. ", e);
        }
        username = usernameCallback.getName();
        password = passwordCallback.getPassword();
         success = validateUserPassword(username, password);
        return success;
}

`
